CPPFLAGS = -c -fno-builtin -fno-rtti -fno-exceptions

.PHONY:  clean

OBJS = multiboot.o system.o Machine.o pic.o Kernel.o IntManager.o main.o  FontMap.o video.o isrs.o  exception.o timer.o PFrameStack.o PhysMManager.o 


all: kernel.elf

kernel.elf: $(OBJS) link.lds
	ld -T link.lds $(OBJS) -o kernel.tmp
	objcopy -O elf32-i386 kernel.tmp kernel.elf
	$(RM) kernel.tmp
	"C:\Program Files\WinImage\winimage.exe" floppy.flp /i kernel.elf /h
	 objdump.exe -D kernel.elf > log.txt
	
clean:
	$(RM) $(OBJS)
	
	
%.o: %.cpp
	g++ $(CPPFLAGS)  $< -o $@
	
video.cpp: system.h video.h
main.cpp: system.h
exception.cpp: exception.h system.h
timer.cpp: timer.h system.h pic.h
isr.cpp: isr.h system.h

	
%.o: %.s
	nasm -f elf  -DLEADING_USCORE $< -o $@